version: "3"
services:
  analyzer:
    container_name: analyzer-main
    build: .
    depends_on:
      - analyzerdb
    links:
      - analyzerdb:analyzerdb
    networks:
      - analyz-network
    ports:
      - "8080:8080"
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://analyzerdb:5432/postgres"
      JDBC_DATABASE_USERNAME: "postgres"
      JDBC_DATABASE_PASSWORD: "postgres"

  analyzerdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - analyz-network

networks:
  analyz-network:
    driver: bridge